

CREATE DATABASE LearnOnline
GO

USE LearnOnline
GO

set dateformat dmy

-- bảng tỉnh thành phố
CREATE TABLE Provinces
(
	ID				Int PRIMARY KEY IDENTITY(1, 1 ),
	ProvincesName	nvarchar(200)   NULL,
)

-- bảng huyện
CREATE TABLE District
(
	ID				Int PRIMARY KEY IDENTITY(1, 1 ),
	ProvincesID		int not null,      -- liên kết khóa ngoại table Provinces
	DistrictName	nvarchar(200)   not NULL,
	FOREIGN KEY (ProvincesID) REFERENCES Provinces(ID) 
)

--Bảng nhóm người dùng
CREATE TABLE UserGroup
(
	ID		Int PRIMARY KEY IDENTITY(1, 1 ),
	Name	nvarchar(100) NOT NULL
)

--Bảng người dùng
CREATE TABLE Users
(
	ID			Int PRIMARY KEY IDENTITY(100, 1 ),
	Avatar		nvarchar(256)		NULL,
	FullName	Nvarchar (50)	NOT NULL,
	Address		Nvarchar (100)  NOT NULL,
	NgaySinh	datetime			NULL,
	Sex			bit					NULL,
	SSN			varchar(15)			NULL,
	Phone		varchar(15)			NULL,
	Email		varchar(150)		NULL,
	ProvincesID	int				NOT NULL,   -- liên kết khóa ngoại table Provinces
	DistrictID	int				NOT NULL,	-- liên kết khóa ngoại table Provinces
	UnitName	nvarchar(100)   NOT NULL,   -- nơi đơn vị công tác
	UserName	varchar(100)	NOT NULL,
	Password	varchar(100)	NOT NULL,
	Status		bit					NULL,
	UserGroupID	int				NOT NULL,	-- liên kết khóa ngoại table Nhóm Người Dùng

	FOREIGN KEY (ProvincesID) REFERENCES Provinces(ID), 
	FOREIGN KEY (DistrictID) REFERENCES District(ID),
	FOREIGN KEY (UserGroupID) REFERENCES UserGroup(ID),
)

--Bảng môn học
CREATE TABLE Subjects
(
	ID			Int PRIMARY KEY IDENTITY(1, 1 ),
	subjectName nvarchar(100) NOT NULL
)

CREATE TABLE Document
(
	ID Int PRIMARY KEY IDENTITY(1, 1 ),
	DocumentName nvarchar(100) NOT NULL,
	LinkDocument varchar(500)	NULL,
	UserID	INT	NOT NULL,		-- liên kết khóa ngoại table Người Dùng
	SubjectsID INT	NOT NULL,		-- liên kết khóa ngoại table Subjects
	
	FOREIGN KEY (SubjectsID) REFERENCES Subjects(ID), 
	FOREIGN KEY (UserID) REFERENCES Users(ID)
)

CREATE TABLE Videos
(
	ID Int PRIMARY KEY IDENTITY(1, 1 ),
	Video nvarchar(100) NOT NULL,
	LinkVideo varchar(500)	NULL,
	UserID	INT	NOT NULL,		-- liên kết khóa ngoại table Người Dùng
	SubjectsID INT	NOT NULL,		-- liên kết khóa ngoại table Subjects
	
	FOREIGN KEY (SubjectsID) REFERENCES Subjects(ID), 
	FOREIGN KEY (UserID) REFERENCES Users(ID)
)

-- Bảng chuyên đề
CREATE TABLE Thematic
(
	ID						Int PRIMARY KEY IDENTITY(1, 1 ),
	SubjectsID				INT				NOT NULL,       -- liên kết khóa ngoại table Môn Học
	UserID					INT				NOT NULL,		-- liên kết khóa ngoại table Người Dùng
	ThematicName			nvarchar(256)   NOT NULL,
	Fees					decimal			NULL,			-- Lệ phí
	NumberOfAccessInMonth	int				NULL,			-- Số lượng truy cập trong tháng
	TotalAccess				int				NULL,			-- Tổng số lượng truy cập
	CreateDate				DateTime		NULL,			
	Status					bit				NULL,

	FOREIGN KEY (SubjectsID) REFERENCES Subjects(ID), 
	FOREIGN KEY (UserID) REFERENCES Users(ID)
)

-- Bảng chi tiết luyện chuyên đề
CREATE TABLE DetailThematic
(
	ID			Int PRIMARY KEY IDENTITY(1, 1 ),
	ThematicID	Int				NOT NULL,       -- liên kết khóa ngoại table Luyện chuyên đề
	DocumentID	Int 			NOT NULL,
	VideoID		Int 			NOT NULL,				
	TitleName	nvarchar(200)	NOT NULL,       -- Tên bài học	
	Status		bit				NULL,

	FOREIGN KEY (ThematicID) REFERENCES Thematic(ID), 
	FOREIGN KEY (DocumentID) REFERENCES Document(ID),
	FOREIGN KEY (VideoID) REFERENCES Videos(ID)
)

-- bảng level
CREATE TABLE Levels
(
	ID	Int PRIMARY KEY IDENTITY(1, 1 ),
	LevelName		nvarchar(256)  NOT NULL
)

-- Bảng đề thi
CREATE TABLE Exam
(
	ID			Int PRIMARY KEY IDENTITY(100, 1 ),
	SubjectsID	Int NOT NULL,					-- liên kết khóa ngoại table Môn Học
	LevelID		Int NOT NULL,					-- liên kết khóa ngoại table cấp độ
	CreateDate	datetime  NULL,
	UpdateDate	datetime  NULL,
	UserCreate	nvarchar(50)  NULL,
	Status		bit		NULL,
	FOREIGN KEY (SubjectsID) REFERENCES Subjects(ID), 
	FOREIGN KEY (LevelID) REFERENCES Levels(ID), 
)

-- Bảng chi tiết đề thi
CREATE TABLE DetailExam
(
	ID			Int PRIMARY KEY IDENTITY(1, 1 ),
	ExamID		Int NOT NULL,				-- liên kết khóa ngoại table Đề thi
	Question	nvarchar(max) NOT NULL,
	OptionA		nvarchar(256)  NULL,
	OptionB		nvarchar(256)  NULL,
	OptionC		nvarchar(256)  NULL,
	OptionD		nvarchar(256)  NULL,
	Answer		nvarchar(256)  NULL,         -- đáp án

	FOREIGN KEY (ExamID) REFERENCES Exam(ID), 
)

-- Bảng kết quả thi
CREATE TABLE ExamResult
(
	ID			Int PRIMARY KEY IDENTITY(1, 1 ),
	UserID		Int			NOT NULL,			-- liên kết khóa ngoại table Người dùng
	LevelID		Int			NOT NULL,			-- liên kết khóa ngoại table Mức độ
	CreateDate	Datetime	NULL,

	FOREIGN KEY (UserID) REFERENCES Users(ID), 
	FOREIGN KEY (LevelID) REFERENCES Levels(ID),
)

-- Bảng kết chi tiết quả thi
CREATE TABLE DetailExamResult
(
	ExamResultID		Int		NOT NULL,	-- liên kết khóa ngoại table Kết quả thi
	SubjectsID			int		NOT NULL,	-- liên kết khóa ngoại table Môn học
	Point				float		NULL,	-- số điểm đạt được			
	WorkTime			int			NULL,	-- thời gian làm bài
	PRIMARY KEY(ExamResultID, SubjectsID),

	FOREIGN KEY (ExamResultID) REFERENCES ExamResult(ID), 
	FOREIGN KEY (SubjectsID) REFERENCES Subjects(ID),
)

-- Bảng Ngân hàng
CREATE TABLE Banks
(
	ID			Int PRIMARY KEY IDENTITY(1, 1 ),
	BankName	nvarchar(200) NOT NULL,
	Stauts		bit				NULL,
)

-- Bảng Xác nhận chuyển tiền
CREATE TABLE ConfirmTransfer
(
	ID					Int PRIMARY KEY IDENTITY(1, 1 ),
	DateOfTransfer		datetime		NULL,		-- ngày chuyển khoản
	AmountTransfer		decimal			NOT NULL,	-- số tiền chuyển
	BankTransferPerson	int				NOT NULL,   -- ngân hàng người chuyển
	BankAccount			varchar(50)		NULL,		-- số tài khoản
	Messages			nvarchar(500)	NULL,
	UsernameEnjoy		varchar(100)	NULL,

	FOREIGN KEY (BankTransferPerson) REFERENCES Banks(ID), 
)


insert into Banks values
(N'Ngân hàng VietcomBank', NULL),
(N'Ngân hàng BIDV', NULL),
(N'Ngân hàng Vietinbank', NULL),
(N'Ngân hàng AGribank', NULL),
(N'Ngân hàng ACB', NULL),
(N'Ngân hàng Đông Á', NULL),
(N'Ngân hàng Techcombank', NULL),
(N'Ngân hàng Sacombank', NULL)

insert into UserGroup values
(N'Học viên'),
(N'Giảng viên'),
(N'Quản trị viên')

insert into Provinces values
(N'HÀ NỘI'),
(N'HỒ CHÍ MINH'),
(N'HẢI PHÒNG'),
(N'ĐÀ NẴNG'),
(N'HÀ GIANG'),
(N'CAO BẰNG'),
(N'LAI CHÂU'),
(N'LÀO CAI'),
(N'TUYÊN QUANG'),
(N'LẠNG SƠN'),
(N'BẮC KẠN'),
(N'THÁI NGUYÊN'),
(N'YÊN BÁI'),
(N'SƠN LA'),
(N'PHÚ THỌ'),
(N'VĨNH PHÚC'),
(N'QUẢNG NINH'),
(N'BẮC GIANG'),
(N'BẮC NINH'),
(N'HẢI DƯƠNG'),
(N'HƯNG YÊN'),
(N'HOÀ BÌNH'),
(N'HÀ NAM'),
(N'NAM ĐỊNH'),
(N'THÁI BÌNH'),
(N'NINH BÌNH'),
(N'THANH HOÁ'),
(N'NGHỆ AN'),
(N'HÀ TĨNH'),
(N'QUẢNG BÌNH'),
(N'QUẢNG TRỊ'),
(N'THỪA THIÊN HUẾ'),
(N'QUẢNG NAM'),
(N'QUẢNG NGÃI'),
(N'KONTUM'),
(N'BÌNH ĐỊNH'),
(N'GIA LAI'),
(N'PHÚ YÊN'),
(N'ĐĂK LĂK'),
(N'KHÁNH HOÀ'),
(N'LÂM ĐỒNG'),
(N'BÌNH PHƯỚC'),
(N'BÌNH DƯƠNG'),
(N'NINH THUẬN'),
(N'TÂY NINH'),
(N'BÌNH THUẬN'),
(N'ĐỒNG NAI'),
(N'LONG AN'),
(N'ĐỒNG THÁP'),
(N'AN GIANG'),
(N'BÀ RỊA-VŨNG TÀU'),
(N'TIỀN GIANG'),
(N'KIÊN GIANG'),
(N'CẦN THƠ'),
(N'BẾN TRE'),
(N'VĨNH LONG'),
(N'TRÀ VINH'),
(N'SÓC TRĂNG'),
(N'BẠC LIÊU'),
(N'CÀ MAU'),
(N'ĐIỆN BIÊN'),
(N'DĂK NÔNG'),
(N'HẬU GIANG');

insert into District values
(1, N'Quận Ba Đình'),
(1, N'Quận Hoàn Kiếm'),
(1, N'Quận Hai Bà Trưng'),
(1, N'Quận Đống Đa'),
(1, N'Quận Tây Hồ'),
(1, N'Quận Cầu Giấy'),
(1, N'Quận Thanh Xuân'),
(1, N'Quận Hoàng Mai'),
(1, N'Quận Long Biên'),
(1, N'Huyện Từ Liêm'),
(1, N'Huyện Thanh Trì'),
(1, N'Huyện Gia Lâm'),
(1, N'Huyện Đông Anh'),
(1, N'Huyện Sóc Sơn'),
(1, N'Thành phố Hà Đông'),
(1, N'Thành phố Sơn Tây'),
(1, N'Huyện Ba Vì'),
(1, N'Huyện Phúc Thọ'),
(1, N'Huyện Thạch Thất'),
(1, N'Huyện Quốc Oai'),
(1, N'Huyện Chương Mỹ'),
(1, N'Huyện Đan Phượng'),
(1, N'Huyện Hoài Đức'),
(1, N'Huyện Thanh Oai'),
(1, N'Huyện Mỹ Đức'),
(1, N'Huyện Ứng Hòa'),
(1, N'Huyện Thường Tín'),
(1, N'Huyện Phú Xuyên'),
(1, N'Huyện Mê Linh'),
(2, N'Quận Một'),
(2, N'Quận Hai'),
(2, N'Quận Ba'),
(2, N'Quận Bốn'),
(2, N'Quận Năm'),
(2, N'Quận Sáu'),
(2, N'Quận Bảy'),
(2, N'Quận Tám'),
(2, N'Quận Chín'),
(2, N'Quận Mười'),
(2, N'Quận Mười một'),
(2, N'Quận Mười hai'),
(2, N'Quận Gò Vấp'),
(2, N'Quận Tân Bình'),
(2, N'Quận Tân Phú'),
(2, N'Quận Bình Thạnh'),
(2, N'Quận Phú Nhuận'),
(2, N'Quận Thủ Đức'),
(2, N'Quận Bình Tân'),
(2, N'Huyện Bình Chánh'),
(2, N'Huyện Củ Chi'),
(2, N'Huyện Hóc Môn'),
(2, N'Huyện Nhà Bè'),
(2, N'Huyện Cần Giờ'),
(3, N'Sở GD&ĐT'),
(3, N'Quận Hồng Bàng'),
(3, N'Quận Lê Chân'),
(3, N'Quận Ngô Quyền'),
(3, N'Quận Kiến An'),
(3, N'Quận Hải An'),
(3, N'Quận Đồ Sơn'),
(3, N'Huyện An Lão'),
(3, N'Huyện Kiến Thụy'),
(3, N'Huyện Thủy Nguyên'),
(3, N'Huyện An Dương'),
(3, N'Huyện Tiên Lãng'),
(3, N'Huyện Vĩnh Bảo'),
(3, N'Huyện Cát Hải'),
(3, N'Huyện Bạch Long Vĩ'),
(3, N'Quận Dương Kinh'),
(4, N'Quận Hải Châu'),
(4, N'Quận Thanh Khê'),
(4, N'Quận Sơn Trà'),
(4, N'Quận Ngũ Hành Sơn'),
(4, N'Quận Liên Chiểu'),
(4, N'Huyện Hoà Vang'),
(4, N'Quận Cẩm Lệ'),
(5, N'Thị xã Hà Giang'),
(5, N'Huyện Đồng Văn'),
(5, N'Huyện Mèo Vạc'),
(5, N'Huyện Yên Minh'),
(5, N'Huyện Quản Bạ'),
(5, N'Huyện Vị Xuyên'),
(5, N'Huyện Bắc Mê'),
(5, N'Huyện Hoàng Su Phì'),
(5, N'Huyện Xín Mần'),
(5, N'Huyện Bắc Quang'),
(5, N'Huyện Quang Bình'),
(6, N'Thị xã Cao Bằng'),
(6, N'Huyện Bảo Lạc'),
(6, N'Huyện Thông Nông'),
(6, N'Huyện Hà Quảng'),
(6, N'Huyện Trà Lĩnh'),
(6, N'Huyện Trùng Khánh'),
(6, N'Huyện Nguyên Bình'),
(6, N'Huyện Hoà An'),
(6, N'Huyện Quảng Uyên'),
(6, N'Huyện Thạch An'),
(6, N'Huyện Hạ Lang'),
(6, N'Huyện Bảo Lâm'),
(6, N'Huyện Phục Hoà'),
(7, N'Thị xã Lai Châu'),
(7, N'Huyện Tam Đường'),
(7, N'Huyện Phong Thổ'),
(7, N'Huyện Sìn Hồ'),
(7, N'Huyện Mường Tè'),
(7, N'Huyện Than Uyên'),
(7, N'Huyện Tân Uyên'),
(8, N'Thành phố Lào Cai'),
(8, N'Huyện Xi Ma Cai'),
(8, N'Huyện Bát Xát'),
(8, N'Huyện Bảo Thắng'),
(8, N'Huyện Sa Pa'),
(8, N'Huyện Văn Bàn'),
(8, N'Huyện Bảo Yên'),
(8, N'Huyện Bắc Hà'),
(8, N'Huyện Mường Khương'),
(9, N'Thị xã Tuyên Quang'),
(9, N'Huyện Na Hang'),
(9, N'Huyện Chiêm Hoá'),
(9, N'Huyện Hàm Yên'),
(9, N'Huyện Yên Sơn'),
(9, N'Huyện Sơn Dương'),
(10, N'Thành phố Lạng Sơn'),
(10, N'Huyện Văn Lãng'),
(10, N'Huyện Bắc Sơn'),
(10, N'Huyện Lộc Bình'),
(10, N'Huyện Chi Lăng'),
(10, N'Huyện Tràng Định'),
(10, N'Huyện Bình Gia'),
(10, N'Huyện Văn Quan'),
(10, N'Huyện Cao Lộc'),
(10, N'Huyện Đình Lập'),
(10, N'Huyện Hữu Lũng'),
(11, N'Thị xã Bắc Kạn'),
(11, N'Huyện Chợ Đồn'),
(11, N'Huyện Bạch Thông'),
(11, N'Huyện Na Rì'),
(11, N'Huyện Ngân Sơn'),
(11, N'Huyện Ba Bể'),
(11, N'Huyện Chợ Mới'),
(11, N'Huyện Pác Nặm'),
(12, N'Sở Giáo dục và Đào tạo'),
(12, N'TP. Thái Nguyên'),
(12, N'Thị xã Sông Công'),
(12, N'Huyện Định Hoá'),
(12, N'Huyện Phú Lương'),
(12, N'Huyện Võ Nhai'),
(12, N'Huyện Đại Từ'),
(12, N'Huyện Đồng Hỷ'),
(12, N'Huyện Phú Bình'),
(12, N'Huyện Phổ Yên'),
(13, N'Thành phố Yên Bái'),
(13, N'Thị xã Nghĩa Lộ'),
(13, N'Huyện Văn Yên'),
(13, N'Huyện Yên Bình'),
(13, N'Huyện Mù Cang Chải'),
(13, N'Huyện Văn Chấn'),
(13, N'Huyện Trấn Yên'),
(13, N'Huyện Trạm Tấu'),
(13, N'Huyện Lục Yên'),
(14, N'Thị xã Sơn La'),
(14, N'Huyện Quỳnh Nhai'),
(14, N'Huyện Mường La'),
(14, N'Huyện Thuận Châu'),
(14, N'Huyện Bắc Yên'),
(14, N'Huyện Phù Yên'),
(14, N'Huyện Mai Sơn'),
(14, N'Huyện Yên Châu'),
(14, N'Huyện Sông Mã'),
(14, N'Huyện Mộc Châu'),
(14, N'Huyện Sốp Cộp'),
(15, N'TP. Việt Trì'),
(15, N'Thị xã Phú Thọ'),
(15, N'Huyện Đoan Hùng'),
(15, N'Huyện Thanh Ba'),
(15, N'Huyện Hạ Hoà'),
(15, N'Huyện Cẩm Khê'),
(15, N'Huyện Yên Lập'),
(15, N'Huyện Thanh Sơn'),
(15, N'Huyện Phù Ninh'),
(15, N'Huyện Lâm Thao'),
(15, N'Huyện Tam Nông'),
(15, N'Huyện Thanh Thủy'),
(15, N'Huyện Tân Sơn'),
(16, N'Sở Giáo dục và Đào tạo'),
(16, N'Thành phố Vĩnh Yên'),
(16, N'Huyện Tam Dương'),
(16, N'Huyện Lập Thạch'),
(16, N'Huyện Vĩnh Tường'),
(16, N'Huyện Yên Lạc'),
(16, N'Huyện Bình Xuyên'),
(16, N'Thị xã Phúc Yên'),
(16, N'Huyện Tam Đảo'),
(17, N'TP. Hạ Long'),
(17, N'Thị xã Cẩm Phả'),
(17, N'Thị xã Uông Bí'),
(17, N'Thị xã Móng Cái'),
(17, N'Huyện Bình Liêu'),
(17, N'Huyện Đầm Hà'),
(17, N'Huyện Hải Hà'),
(17, N'Huyện Tiên Yên'),
(17, N'Huyện Ba Chẽ'),
(17, N'Huyện Đông Triều'),
(17, N'Huyện Yên Hưng'),
(17, N'Huyện Hoành Bồ'),
(17, N'Huyện Vân Đồn'),
(17, N'Huyện Cô Tô'),
(18, N'Thành phố Bắc Giang'),
(18, N'Huyện Yên Thế'),
(18, N'Huyện Lục Ngạn'),
(18, N'Huyện Sơn Động'),
(18, N'Huyện Lục Nam'),
(18, N'Huyện Tân Yên'),
(18, N'Huyện Hiệp Hoà'),
(18, N'Huyện Lạng Giang'),
(18, N'Huyện Việt Yên'),
(18, N'Huyện Yên Dũng'),
(19, N'Sở Giáo dục và Đào tạo'),
(19, N'Thành phố Bắc Ninh'),
(19, N'Huyện Yên Phong'),
(19, N'Huyện Quế Võ'),
(19, N'Huyện Tiên Du'),
(19, N'Huyện Từ Sơn'),
(19, N'Huyện Thuận Thành'),
(19, N'Huyện Gia Bình'),
(19, N'Huyện Lương Tài'),
(20, N'Thành phố Hải Dương'),
(20, N'Huyện Chí Linh'),
(20, N'Huyện Nam Sách'),
(20, N'Huyện Kinh Môn'),
(20, N'Huyện Gia Lộc'),
(20, N'Huyện Tứ Kỳ'),
(20, N'Huyện Thanh Miện'),
(20, N'Huyện Ninh Giang'),
(20, N'Huyện Cẩm Giàng'),
(20, N'Huyện Thanh Hà'),
(20, N'Huyện Kim Thành'),
(20, N'Huyện Bình Giang'),
(21, N'Thị xã Hưng Yên'),
(21, N'Huyện Kim Động'),
(21, N'Huyện Ân Thi'),
(21, N'Huyện Khoái Châu'),
(21, N'Huyện Yên Mỹ'),
(21, N'Huyện Tiên Lữ'),
(21, N'Huyện Phù Cừ'),
(21, N'Huyện Mỹ Hào'),
(21, N'Huyện Văn Lâm'),
(21, N'Huyện Văn Giang'),
(22, N'Thành phố Hoà Bình'),
(22, N'Huyện Đà Bắc'),
(22, N'Huyện Mai Châu'),
(22, N'Huyện Tân Lạc'),
(22, N'Huyện Lạc Sơn'),
(22, N'Huyện Kỳ Sơn'),
(22, N'Huyện Lương Sơn'),
(22, N'Huyện Kim Bôi'),
(22, N'Huyện Lạc Thuỷ'),
(22, N'Huyện Yên Thuỷ'),
(22, N'Huyện Cao Phong'),
(23, N'Thành phố Phủ Lý'),
(23, N'Huyện Duy Tiên'),
(23, N'Huyện Kim Bảng'),
(23, N'Huyện Lý Nhân'),
(23, N'Huỵện Thanh Liêm'),
(23, N'Huyện Bình Lục'),
(24, N'TP. Nam Định'),
(24, N'Huyện Mỹ Lộc'),
(24, N'Huyện Xuân Trường'),
(24, N'Huyện Giao Thủy'),
(24, N'Huyện ý Yên'),
(24, N'Huyện Vụ Bản'),
(24, N'Huyện Nam Trực'),
(24, N'Huyện Trực Ninh'),
(24, N'Huyện Nghĩa Hưng'),
(24, N'Huyện Hải Hậu'),
(25, N'Thành phố Thái Bình'),
(25, N'Huyện Quỳnh Phụ'),
(25, N'Huyện Hưng Hà'),
(25, N'Huyện Đông Hưng'),
(25, N'Huyện Vũ Thư'),
(25, N'Huyện Kiến Xương'),
(25, N'Huyện Tiền Hải'),
(25, N'Huyện Thái Thuỵ'),
(26, N'Thành phố Ninh Bình'),
(26, N'Thị xã Tam Điệp'),
(26, N'Huyện Nho Quan'),
(26, N'Huyện Gia Viễn'),
(26, N'Huyện Hoa Lư'),
(26, N'Huyện Yên Mô'),
(26, N'Huyện Kim Sơn'),
(26, N'Huyện Yên Khánh'),
(27, N'TP.Thanh Hoá'),
(27, N'Thị xã Bỉm Sơn'),
(27, N'Thị xã Sầm Sơn'),
(27, N'Huyện Quan Hoá'),
(27, N'Huyện Quan Sơn'),
(27, N'Huyện Mường Lát'),
(27, N'Huyện Bá Thước'),
(27, N'Huyện Thường Xuân'),
(27, N'Huyện Như Xuân'),
(27, N'Huyện Như Thanh'),
(27, N'Huyện Lang Chánh'),
(27, N'Huyện Ngọc Lặc'),
(27, N'Huyện Thạch Thành'),
(27, N'Huyện Cẩm Thủy'),
(27, N'Huyện Thọ Xuân'),
(27, N'Huyện Vĩnh Lộc'),
(27, N'Huyện Thiệu Hoá'),
(27, N'Huyện Triệu Sơn'),
(27, N'Huyện Nông Cống'),
(27, N'Huyện Đông Sơn'),
(27, N'Huyện Hà Trung'),
(27, N'Huyện Hoằng Hoá'),
(27, N'Huyện Nga Sơn'),
(27, N'Huyện Hậu Lộc'),
(27, N'Huyện Quảng Xương'),
(27, N'Huyện Tĩnh Gia'),
(27, N'Huyện Yên Định'),
(28, N'Thành phố Vinh'),
(28, N'Thị xã Cửa Lò'),
(28, N'Huyện Quỳ Châu'),
(28, N'Huyện Quỳ Hợp'),
(28, N'Huyện Nghĩa Đàn'),
(28, N'Huyện Quỳnh Lưu'),
(28, N'Huyện Kỳ Sơn'),
(28, N'Huyện Tương Dương'),
(28, N'Huyện Con Cuông'),
(28, N'Huyện Tân Kỳ'),
(28, N'Huyện Yên Thành'),
(28, N'Huyện Diễn Châu'),
(28, N'Huyện Anh Sơn'),
(28, N'Huyện Đô Lương'),
(28, N'Huyện Thanh Chương'),
(28, N'Huyện Nghi Lộc'),
(28, N'Huyện Nam Đàn'),
(28, N'Huyện Hưng Nguyên'),
(28, N'Huyện Quế Phong'),
(29, N'Thành phố Hà Tĩnh'),
(29, N'Thị xã Hồng Lĩnh'),
(29, N'Huyện Hương Sơn'),
(29, N'Huyện Đức Thọ'),
(29, N'Huyện Nghi Xuân'),
(29, N'Huyện Can Lộc'),
(29, N'Huyện Hương Khê'),
(29, N'Huyện Thạch Hà'),
(29, N'Huyện Cẩm Xuyên'),
(29, N'Huyện Kỳ Anh'),
(29, N'Huyện Vũ Quang'),
(29, N'Huyện Lộc Hà'),
(30, N'Thành phố Đồng Hới'),
(30, N'Huyện Tuyên Hoá'),
(30, N'Huyện Minh Hoá'),
(30, N'Huyện Quảng Trạch'),
(30, N'Huyện Bố Trạch'),
(30, N'Huyện Quảng Ninh'),
(30, N'Huyện Lệ Thuỷ'),
(31, N'Thị xã Đông Hà'),
(31, N'Thị xã Quảng Trị'),
(31, N'Huyện Vĩnh Linh'),
(31, N'Huyện Gio Linh'),
(31, N'Huyện Cam Lộ'),
(31, N'Huyện Triệu Phong'),
(31, N'Huyện Hải Lăng'),
(31, N'Huyện Hướng Hoá'),
(31, N'Huyện Đăk Rông'),
(31, N'Huyện đảo Cồn cỏ'),
(32, N'Thành phố Huế'),
(32, N'Huyện Phong Điền'),
(32, N'Huyện Hương Trà'),
(32, N'Huyện Phú Vang'),
(32, N'Huyện Hương Thuỷ'),
(32, N'Huyện Nam Đông'),
(32, N'Huyện A Lưới'),
(32, N'Huyện Quảng Điền 3307 Huyện Phú Lộc'),
(33, N'Thành phố Tam Kỳ'),
(33, N'Thị xã Hội An'),
(33, N'Huyện Duy Xuyên'),
(33, N'Huyện Điện Bàn'),
(33, N'Huyện Đại Lộc'),
(33, N'Huyện Quế Sơn'),
(33, N'Huyện Hiệp Đức'),
(33, N'Huyện Thăng Bình'),
(33, N'Huyện Núi Thành'),
(33, N'Huyện Tiên Phước'),
(33, N'Huyện Bắc Trà My'),
(33, N'Huyện Đông Giang'),
(33, N'Huyện Nam Giang'),
(33, N'Huyện Phước Sơn'),
(33, N'Huyện Nam Trà My'),
(33, N'Huyện Tây Giang'),
(33, N'Huyện Phú Ninh'),
(33, N'Huyện Nông Sơn'),
(34, N'TP.Quảng Ngãi'),
(34, N'Huyện Lý Sơn'),
(34, N'Huyện Bình Sơn'),
(34, N'Huyện Trà Bồng'),
(34, N'Huyện Sơn Tịnh'),
(34, N'Huyện Sơn Hà'),
(34, N'Huyện Tư Nghĩa'),
(34, N'Huyện Nghĩa Hành'),
(34, N'Huyện Minh Long'),
(34, N'Huyện Mộ Đức'),
(34, N'Huyện Đức Phổ'),
(34, N'Huyện Ba Tơ'),
(34, N'Huyện Sơn Tây'),
(34, N'Huyện Tây Trà'),
(35, N'Thị xã KonTum'),
(35, N'Huyện Đăk Glei'),
(35, N'Huyện Ngọc Hồi'),
(35, N'Huyện Đăk Tô'),
(35, N'Huyện Sa Thầy'),
(35, N'Huyện Kon Plong'),
(35, N'Huyện Đăk Hà'),
(35, N'Huyện Kon Rộy'),
(35, N'Huyện Tu Mơ Rông'),
(36, N'Thành phố Quy Nhơn'),
(36, N'Huyện An Lão'),
(36, N'Huyện Hoài Ân'),
(36, N'Huyện Hoài Nhơn'),
(36, N'Huyện Phù Mỹ'),
(36, N'Huyện Phù Cát'),
(36, N'Huyện Vĩnh Thạnh'),
(36, N'Huyện Tây Sơn'),
(36, N'Huyện Vân Canh'),
(36, N'Huyện An Nhơn'),
(36, N'Huyện Tuy Phước'),
(37, N'Thành phố Pleiku'),
(37, N'Huyện Chư Păh'),
(37, N'Huyện Mang Yang'),
(37, N'Huyện Kbang'),
(37, N'Thị xã An Khê'),
(37, N'Huyện Kông Chro'),
(37, N'Huyện Đức Cơ'),
(37, N'Huyện Chưprông'),
(37, N'Huyện Chư Sê'),
(37, N'Huyện Ayunpa'),
(37, N'Huyện Krông Pa'),
(37, N'Huyện Ia Grai'),
(37, N'Huyện Đăk Đoa'),
(37, N'Huyện Ia Pa'),
(37, N'Huyện Đăk Pơ'),
(37, N'Huyện Phú Thiện'),
(38, N'Thị xã Tuy Hoà'),
(38, N'Huyện Đồng Xuân'),
(38, N'Huyện Sông Cầu'),
(38, N'Huyện Tuy An'),
(38, N'Huyện Sơn Hoà'),
(38, N'Huyện Sông Hinh'),
(38, N'Huyện Đông Hoà'),
(38, N'Huyện Phú Hoà'),
(38, N'Huyện Tây Hoà'),
(39, N'TP.Buôn Ma Thuột'),
(39, N'Huyện Ea H Leo'),
(39, N'Huyện Krông Buk'),
(39, N'Huyện Krông Năng'),
(39, N'Huyện Ea Súp'),
(39, N'Huyện Cư M gar'),
(39, N'Huyện Krông Pắc'),
(39, N'Huyện Ea Kar'),
(39, N'Huyện M''Đrăk'),
(39, N'Huyện Krông Ana'),
(39, N'Huyện Krông Bông'),
(39, N'Huyện Lăk'),
(39, N'Huyện Buôn Đôn'),
(39, N'Huyện Cư Kuin'),
(40, N'Thành phố Nha Trang'),
(40, N'Huyện Vạn Ninh'),
(40, N'Huyện Ninh Hoà'),
(40, N'Huyện Diên Khánh'),
(40, N'Huyện Khánh Vĩnh'),
(40, N'Thị xã Cam Ranh'),
(40, N'Huyện Khánh Sơn'),
(40, N'Huyện Trường Sa'),
(40, N'Huyện Cam Lâm'),
(41, N'Thành phố Đà Lạt'),
(41, N'Thị xã. Bảo Lộc'),
(41, N'Huyện Đức Trọng'),
(41, N'Huyện Di Linh'),
(41, N'Huyện Đơn Dương'),
(41, N'Huyện Lạc Dương'),
(41, N'Huyện Đạ Huoai'),
(41, N'Huyện Đạ Tẻh'),
(41, N'Huyện Cát Tiên'),
(41, N'Huyện Lâm Hà'),
(41, N'Huyện Bảo Lâm'),
(41, N'Huyện Đam Rông'),
(42, N'Thị xã Đồng Xoài'),
(42, N'Huyện Đồng Phú'),
(42, N'Huyện Chơn Thành'),
(42, N'Huyện Bình Long'),
(42, N'Huyện Lộc Ninh'),
(42, N'Huyện Bù Đốp'),
(42, N'Huyện Phước Long'),
(42, N'Huyện Bù Đăng'),
(43, N'Thị xã Thủ Dầu Một'),
(43, N'Huyện Bến Cát'),
(43, N'Huyện Tân Uyên'),
(43, N'Huyện Thuận An'),
(43, N'Huyện Dĩ An'),
(43, N'Huyện Phú Giáo'),
(43, N'Huyện Dầu Tiếng'),
(44, N'TP.Phan Rang - Tháp Chàm'),
(44, N'Huyện Ninh Sơn'),
(44, N'Huyện Ninh Hải'),
(44, N'Huyện Ninh Phước'),
(44, N'Huyện Bác ái'),
(44, N'Huyện Thuận Bắc'),
(45, N'Thị xã Tây Ninh'),
(45, N'Huyện Tân Biên'),
(45, N'Huyện Tân Châu'),
(45, N'Huyện Dương Minh Châu'),
(45, N'Huyện Châu Thành'),
(45, N'Huyện Hoà Thành'),
(45, N'Huyện Bến Cầu'),
(45, N'Huyện Gò Dầu'),
(45, N'Huyện Trảng Bàng'),
(46, N'Thành phố Phan Thiết'),
(46, N'Huyện Tuy Phong'),
(46, N'Huyện Bắc Bình'),
(46, N'Huyện Hàm Thuận Bắc'),
(46, N'Huyện Hàm Thuận Nam'),
(46, N'Huyện Hàm Tân'),
(46, N'Huyện Đức Linh'),
(46, N'Huyện Tánh Linh'),
(46, N'Huyện đảo Phú Quý'),
(46, N'Thị xã LaGi'),
(47, N'Thành phố Biên Hoà'),
(47, N'Huyện Vĩnh Cửu'),
(47, N'Huyện Tân Phú'),
(47, N'Huyện Định Quán'),
(47, N'Huyện Thống Nhất'),
(47, N'Thị xã Long Khánh'),
(47, N'Huyện Xuân Lộc'),
(47, N'Huyện Long Thành'),
(47, N'Huyện Nhơn Trạch'),
(47, N'Huyện Trảng Bom'),
(47, N'Huyện Cẩm Mỹ'),
(48, N'Thị xã Tân An'),
(48, N'Huyện Vĩnh Hưng'),
(48, N'Huyện Mộc Hoá'),
(48, N'Huyện Tân Thạnh'),
(48, N'Huyện Thạnh Hoá'),
(48, N'Huyện Đức Huệ'),
(48, N'Huyện Đức Hoà'),
(48, N'Huyện Bến Lức'),
(48, N'Huyện Thủ Thừa'),
(48, N'Huyện Châu Thành'),
(48, N'Huyện Tân Trụ'),
(48, N'Huyện Cần Đước'),
(48, N'Huyện Cần Giuộc'),
(48, N'Huyện Tân Hưng'),
(49, N'Thành phố Cao Lãnh'),
(49, N'Thị xã Sa Đéc'),
(49, N'Huyện Tân Hồng'),
(49, N'Huyện Hồng Ngự'),
(49, N'Huyện Tam Nông'),
(49, N'Huyện Thanh Bình'),
(49, N'Huyện Cao Lãnh'),
(49, N'Huyện Lấp Vò'),
(49, N'Huyện Tháp Mười'),
(49, N'Huyện Lai Vung'),
(49, N'Huyện Châu Thành'),
(50, N'TP.Long Xuyên'),
(50, N'Thị xã Châu Đốc'),
(50, N'Huyện An Phú'),
(50, N'Huyện Tân Châu'),
(50, N'Huyện Phú Tân'),
(50, N'Huyện Tịnh Biên'),
(50, N'Huyện Tri Tôn'),
(50, N'Huyện Châu Phú'),
(50, N'Huyện Chợ Mới'),
(50, N'Huyện Châu Thành'),
(50, N'Huyện Thoại Sơn'),
(51, N'Thành phố Vũng Tàu'),
(51, N'Thị xã Bà Rịa'),
(51, N'Huyện Xuyên Mộc'),
(51, N'Huyện Long Điền'),
(51, N'Huyện Côn Đảo'),
(51, N'Huyện Tân Thành'),
(51, N'Huyện Châu Đức'),
(51, N'Huyện Đất Đỏ'),
(52, N'Thành phố Mỹ Tho'),
(52, N'Thị xã Gò Công'),
(52, N'Huyện Cái Bè'),
(52, N'Huyện Cai Lậy'),
(52, N'Huyện Châu Thành'),
(52, N'Huyện Chợ Gạo'),
(52, N'Huyện Gò Công Tây'),
(52, N'Huyện Gò Công Đông'),
(52, N'Huyện Tân Phước'),
(52, N'Huyện Tân Phú Đông'),
(53, N'Thành phố Rạch Giá'),
(53, N'Thị xã Hà Tiên'),
(53, N'Huyện Kiên Lương'),
(53, N'Huyện Hòn Đất'),
(53, N'Huyện Tân Hiệp'),
(53, N'Huyện Châu Thành'),
(53, N'Huyện Giồng Riềng'),
(53, N'Huyện Gò Quao'),
(53, N'Huyện An Biên'),
(53, N'Huyện An Minh'),
(53, N'Huyện Vĩnh Thuận'),
(53, N'Huyện Phú Quốc'),
(53, N'Huyện Kiên Hải'),
(53, N'Huyện U minh Thượng'),
(54, N'Quận Ninh Kiều'),
(54, N'Quận Bình Thuỷ'),
(54, N'Quận Cái Răng'),
(54, N'Quận Ô Môn'),
(54, N'Huyện Phong Điền'),
(54, N'Huyện Cờ Đỏ'),
(54, N'Huyện Vĩnh Thạnh'),
(54, N'Huỵện Thốt Nốt'),
(55, N'Thị xã Bến Tre'),
(55, N'Huyện Châu Thành'),
(55, N'Huyện Chợ Lách'),
(55, N'Huyện Mỏ Cày'),
(55, N'Huyện Giồng Trôm'),
(55, N'Huyện Bình Đại'),
(55, N'Huyện Ba Tri'),
(55, N'Huyện Thạnh Phú'),
(56, N'Thị xã Vĩnh Long'),
(56, N'Huyện Long Hồ'),
(56, N'Huyện Mang Thít'),
(56, N'Huyện Bình Minh'),
(56, N'Huyện Tam Bình'),
(56, N'Huyện Trà Ôn'),
(56, N'Huyện Vũng Liêm'),
(56, N'Huyện Bình Tân'),
(57, N'Thị xã Trà Vinh'),
(57, N'Huyện Càng Long'),
(57, N'Huyện Cầu Kè'),
(57, N'Huyện Tiểu Cần'),
(57, N'Huyện Châu Thành'),
(57, N'Huyện Trà Cú'),
(57, N'Huyện Cầu Ngang'),
(57, N'Huyện Duyên Hải'),
(58, N'Thành phố Sóc Trăng'),
(58, N'Huyện Kế Sách'),
(58, N'Huyện Mỹ Tú'),
(58, N'Huyện Mỹ Xuyên'),
(58, N'Huyện Thạnh Trị'),
(58, N'Huyện Long Phú'),
(58, N'Huyện Vĩnh Châu'),
(58, N'Huyện Cù Lao Dung'),
(58, N'Huyện Ngã Năm'),
(58, N'Huyện Châu Thành'),
(59, N'Thị xã Bạc Liêu'),
(59, N'Huyện Vĩnh Lợi'),
(59, N'Huyện Hồng Dân'),
(59, N'Huyện Giá Rai'),
(59, N'Huyện Phước Long'),
(59, N'Huyện Đông Hải'),
(59, N'Huyện Hoà Bình'),
(60, N'Thành phố Cà Mau'),
(60, N'Huyện Thới Bình'),
(60, N'Huyện U Minh'),
(60, N'Huyện Trần Văn Thời'),
(60, N'Huyện Cái Nước'),
(60, N'Huyện Đầm Dơi'),
(60, N'Huyện Ngọc Hiển'),
(60, N'Huyện Năm Căn'),
(60, N'Huyện Phú Tân'),
(61, N'TP. Điện Biên Phủ'),
(61, N'Thị xã Mường Lay'),
(61, N'Huyện Điện Biên'),
(61, N'Huyện Tuần Giáo'),
(61, N'Huyện Mường Chà'),
(61, N'Huyện Tủa Chùa'),
(61, N'Huyện Điện Biên Đông'),
(61, N'Huyện Mường Nhé'),
(61, N'Huyện Mường Ảng'),
(62, N'Thị xã Gia Nghĩa'),
(62, N'Huyện Dăk RLấp'),
(62, N'Huyện Dăk Mil'),
(62, N'Huyện Cư Jút'),
(62, N'Huyện Dăk Song'),
(62, N'Huyện Krông Nô'),
(62, N'Huyện Dăk GLong'),
(62, N'Huyện Tuy Đức'),
(63, N'Thị xã Vị Thanh'),
(63, N'Huyện Vị Thuỷ'),
(63, N'Huyện Long Mỹ'),
(63, N'Huyện Phụng Hiệp'),
(63, N'Huyện Châu Thành'),
(63, N'Huyện Châu Thành A'),
(63, N'Thị xã Ngã Bảy');

insert into Users values
(NULL, N'Nguyễn Văn Thuyền', N'72/10A Tây Thạnh', '10/04/1995', 1, '221393524', '01672102464', 'thuyenbu@gmail.com', 2, 45, N'Trường ĐH Công Nghệ Thông Tin', 'thuyenbu', '1', 1, 1),
(NULL, N'Trần Thạch Thảo', N'72/10A Tây Thạnh', NULL, 1, NULL, NULL, 'thaotran@gmail.com', 2, 45, N'Trường ĐH Công Nghệ Thông Tin', 'thaotran', '1', 1, 2)

insert into Levels values
(N'Cập độ khó'),
(N'Cập đô trung bình'),
(N'Cập độ dễ')